# Generated by Django 2.2.2 on 2019-08-18 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, max_length=1024, null=True)),
                ('pagenumber', models.IntegerField(blank=True, null=True)),
                ('notetime', models.DateTimeField(blank=True, default=None)),
                ('noter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='notelist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('belong_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('open_id', models.CharField(max_length=32)),
                ('nickname', models.CharField(blank='佚名', default='佚名', max_length=256, null='佚名')),
                ('headlogo', models.FileField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
