# Generated by Django 2.2.2 on 2019-08-21 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_userinfo_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='note',
        ),
    ]
