# Generated by Django 2.2.2 on 2019-08-21 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_remove_userinfo_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='noteinfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='firstapp.Userinfo'),
        ),
    ]
