# Generated by Django 2.2.2 on 2019-08-21 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_artical_noteinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='noteinfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='noterlist', to='firstapp.Userinfo'),
        ),
    ]
