# Generated by Django 2.2.2 on 2019-08-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20190821_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='author',
            field=models.CharField(blank='无名', max_length=100, null='无名'),
        ),
        migrations.AlterField(
            model_name='artical',
            name='pagenumber',
            field=models.IntegerField(blank='0', null='0'),
        ),
    ]
