# Generated by Django 2.2.2 on 2019-08-26 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20190826_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk', models.CharField(blank=True, max_length=240, null=True)),
                ('talker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='commentlist', to='firstapp.Userinfo')),
                ('artical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='articalcomment', to='firstapp.Artical')),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='headlogo',
            field=models.FileField(blank=True, default='/static/images/headlogo.png', null=True, upload_to='images'),
        ),
    ]
