# Generated by Django 2.2.2 on 2019-08-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20190826_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='talktime',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
