# Generated by Django 2.2.2 on 2019-08-27 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_comment_talktime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='artical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='artical_comment', to='firstapp.Artical'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='talker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='talker_userinfo', to='firstapp.Userinfo'),
        ),
    ]
