# Generated by Django 2.2.2 on 2019-08-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_auto_20190828_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='headlogo',
            field=models.FileField(blank=True, default='/static/images/headlogo.png', null=True, upload_to=''),
        ),
    ]
