# Generated by Django 2.2.2 on 2019-08-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_auto_20190828_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='headlogo',
            field=models.ImageField(blank=True, default='/static/images/headlogo.png', null=True, upload_to=''),
        ),
    ]
