# Generated by Django 2.2.2 on 2019-08-29 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_auto_20190828_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='noteinfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='firstapp.Userinfo', verbose_name='noterlist'),
        ),
        migrations.AlterField(
            model_name='artical',
            name='noter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL, verbose_name='notelist'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='artical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='firstapp.Artical', verbose_name='artical_comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='talker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='firstapp.Userinfo', verbose_name='talker_userinfo'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='belong_to',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='profile'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='headlogo',
            field=models.ImageField(blank=True, default='/static/images/headlogo.png', null=True, upload_to='images'),
        ),
    ]
