# Generated by Django 2.2.2 on 2019-08-29 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_auto_20190830_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='noteinfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='noterlist', to='firstapp.Userinfo'),
        ),
        migrations.AlterField(
            model_name='artical',
            name='noter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='notelist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='artical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='artical_comment', to='firstapp.Artical'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='talker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='talker_userinfo', to='firstapp.Userinfo'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='belong_to',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
