"""
Django settings for website project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from .base import *

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':'backend',
        'USER':'joker',
        'PASSWORD':os.environ['DATABASE_PASSWORD'],
        'HOST':'127.0.0.1',
        'PORT':'3306',
        'OPTIONS': {
             "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
#     os.path.join(BASE_DIR, 'media'),
# ]
WX_APP_SECRET = os.environ['WX_APP_SECRET']
LOGIN_URL = '49.235.231.49'
EMAIL_USE_SSL = True
EMAIL_HOST = 'smtp.qq.com'  # 如果是 163 改成 smtp.163.com
EMAIL_PORT = 465
EMAIL_HOST_USER = 'dk_dante@qq.com' # 帐号
EMAIL_HOST_PASSWORD = os.environ['EMAIL_HOST_PASSWORD']  # 密码
DEFAULT_FROM_EMAIL = '站长邮箱 <dk_dante@qq.com>'

ADMINS=(
   ('admin','dk_dante@qq.com'),
)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/home/mysite/debug.log',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
        }
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
